### ISSUE TITLE
movement stops tracking for certain applications

### ISSUE THREAD

**Issue by Zackerias** [simphax/Touchmote#101]
everything is working great and binds work and everything except when I open Valorant it immediately stops tracking movement, however other buttons work as they should within the game.

**Comment by Ryochan7** [comment]
Suffering pain from this issue in a different project. TLDR: Valorant actively blocks events generated with SendInput.

https://github.com/Ryochan7/DS4Windows/issues/1629

**Comment by Zackerias** [comment]
shoot alright, thanks man.
