### ISSUE TITLE
How do I reset settings?

### ISSUE THREAD

**Issue by Sawtaytoes** [simphax/Touchmote#109]
I disabled a bunch of default settings to test something, and there's no way to reset them back.

Is there a `settings.json` file somewhere?

I also want to know if I wanna backup my configuration data.

**Comment by simphax** [comment]
Yes the settings.json file is located next to the Touchmote.exe in the programs folder. Turn off Touchmote, delete the settings.json and start Touchmote again and it should reset to default settings.

**Comment by Sawtaytoes** [comment]
To fix it, I uninstalled and reinstalled because the default JSON file was overwritten.
