### ISSUE TITLE
Incompatible with other Xinput wrappers, like ScpToolKit

### ISSUE THREAD

**Issue by spinningacorn** [simphax/Touchmote#76]
I'm not sure if this is an issue with ScpToolKit or with Touchmote, but since Touchmote still lacks any option to define wich Xbox Controller should it take (or skip), which would fix this problem, I decided to report this.

My use case: I depend on ScpToolKit to use my DualShock3 as my main controller for most uses. Recently I tried to hook up a Wiimote through Touchmote, but the input mapping both use the same slot.

DS3 works normally if I close Touchmote (and turn the Wiimote off), and the Wiimote through Touchmote works normally if I turn my DS3 off, but together, they send input to the same Xbox Controller slot.
The inputs in the DS3 become intermittent (as if all buttons were turbo) when Touchmote is working, and the axis start to wiggle on the Xbox emulation of Touchmote when the DS3 is present.

Sometimes, multiple ghost Xbox Controllers appear on my device list (four at the moment, but I only have 1 DS3 and 1 Wiimote connected. Something's buggy here). And yet, both devices still input to the same first slot.

Would you consider adding options to define which Xbox Controller slot to use, or which to skip? Maybe something like "force slot 2", so people using another Xinput device mainly could use Touchmote additionally without having to break their current setup?

Thanks in advance!

**Comment by micahrlee** [comment]
I am seeing this issue still. Is there any progress on this? It's a problem for people with multiple xinput controllers, which is almost all of them these days.
