### ISSUE TITLE
Windows 10 Touch Problem

### ISSUE THREAD

**Issue by ruhollahkuhsar** [simphax/Touchmote#87]
Hi. I've installed touchmote on Windows 10 but i can't use the touch mode correctly. I get black screen wherever i move the touch cursor. Here is the image
http://uupload.ir/files/xbii_touchmote.jpg

Can you help me plz? 
By the way, Thanks for the project. I've used it on win 7 and i loved it

**Comment by flytech01** [comment]
Update your video driver! HnD

**Comment by ruhollahkuhsar** [comment]
I have GeForce 210 and driver is up to date

**Comment by ruhollahkuhsar** [comment]
An OSD opens with touchmote and when i close it, the touch cursor disappears, but cursor movement and Main &  Slave touch work

**Comment by ruhollahkuhsar** [comment]
The black tiles problem solved by downgrading vga driver to one i used on win 7. But now i can't touch (click). I can drag & drop, right click, scroll and other gestures. But i can't touch anything to open or select it

**Comment by flytech01** [comment]
Try to setup in control settings A button = left mouse click and B = right mouse click 😊 HnD

**Comment by ruhollahkuhsar** [comment]
Thanks for reply. But mouse cursor is separate from touch cursor. If i set A & B to mouse left and right, it clicks where  mouthese is, not the touch. I tried it on another pc with Windows 10 and it didn't work on that either

**Comment by simphax** [comment]
Touch emulation for windows 10 is fixed in beta 15 :)
